/*
 * Copyright (c) 2019 Mohamed Alaa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 */

package mohamedalaa.mautils.room_gson_annotation;

import com.maproductions.mohamedalaa.library_common_annotations.MAParameterizedKClass;

import java.lang.annotation.ElementType;
import java.lang.annotation.Repeatable;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * <b>VIP Notes</b> <br/>
 * <ul>
 *     <li>
 *         Creates type converter for the specified type defined in {@link #value} isa.
 *     </li>
 *     <li>
 *         Uses only from the annotated class it's simple name so that the type converter
 *         generated by it has a simple name of "MAAutoTypeConverters${AnnotatedClassName}"
 *         and has it's package path isa.
 *     </li>
 * </ul>
 *
 * <b>How to use</b> <br/>
 * <ul>
 *     <li>
 *         In order for the Room database to use the generated classes from the below annotation
 *         Then you have to have all classes annotated with below annotation in a module
 *         that the Room database have it as a dependency isa.
 *     </li>
 * </ul>
 *
 * @see MARoomGsonTypeConverter
 */
@Repeatable(MARoomGsonTypeConverterType.Container.class)
@Retention(RetentionPolicy.SOURCE)
@Target({ElementType.TYPE})
public @interface MARoomGsonTypeConverterType {

    MAParameterizedKClass value();

    /**
     * <B>Shouldn't be used at all</B> except by the developer of the library and inside
     * the annotation processor only isa.
     */
    @Retention(RetentionPolicy.SOURCE)
    @Target({ElementType.TYPE})
    @interface Container {
        MARoomGsonTypeConverterType[] value();
    }

}
